### ISSUE TITLE
[Kitty] Error: open /dev/tty: no such device or address

### ISSUE THREAD

**Issue by ogios** [adelarsq/image_preview.nvim#11]
running it directly result in nothing, so i check the code and get the command:
```
:!kitten @ launch --type=window kitten icat --hold '/home/ogios/.config/eww/ava.jpg'
Error: open /dev/tty: no such device or address
shell returned 1
```
i run it in kitty terminal bash shell, it worked, but run it in nvim doesn't
what should i do?

**Comment by vaaako** [comment]
you need to enable "remote control" _(the error message for some reason doesn't show up on neovim)_
you can achieve this by either editing `kitty.conf` or adding `kitty -o allow_remote_control=true` to your command
for example, the command you sent, becomes: `kitty -o allow_remote_control=true kitten @ launch --type=window kitten icat --hold '/home/ogios/.config/eww/ava.jpg'`

now, you have three options:
- wait for the devs fix this
- make your own build
- adding this custom command to your file manager _(if you use nvim-tree i can help you with that)_

**Comment by ogios** [comment]
i've set `allow_remote_control yes` in `kitty.conf`
but can not open image in current kitty window using `!kitten @ launch --type=window kitten icat --hold '/home/ogios/.config/eww/ava.jpg'`, i have to open another kitty window `!kitty kitten @ launch --type=window kitten icat --hold '/home/ogios/.config/eww/ava.jpg'`

**Comment by vaaako** [comment]
did you try adding `kitty -o allow_remote_control=true` on vim?

**Comment by mejistus** [comment]
> did you try adding `kitty -o allow_remote_control=true` on vim?

I encountered the same problem that ogios mentioned. It worked after I added kitty -o allow_remote_control=true.Thanks a lot!
