### ISSUE TITLE
Oil.nvim support

### ISSUE THREAD

**Issue by domizianooo** [adelarsq/image_preview.nvim#12]
Is there a way to integrate this into the `oil.nvim` plugin to show images when navigating the file tree?

**Comment by chetra-seng** [comment]
@DomizianoScarcelli may I ask how you made it work?

**Comment by domizianooo** [comment]
> @DomizianoScarcelli may I ask how you made it work?

Hi, I'm actually not using this plugin or oil anymore, but I remember closing the issue because I found out (in the readme) that oil was already supported. I didn't remember if I made it work, but anyway this was (part of) my config for oil.nvim using kitty:

```lua
require("oil").setup({
    -- ... stuff here
    keymaps = {
       -- ... other keymaps
        ["gp"] = require('image_preview').PreviewImageOil()
    },
})

```
