### ISSUE TITLE
Preview doesn't work in Tmux

### ISSUE THREAD

**Issue by chetra-seng** [adelarsq/image_preview.nvim#14]
Just try this plugin and it worked like magic. However, it doesn't seem to work when using with tmux. I'm not sure if there's an issue with tmux or something. Hope you can explain this issue :)

**Comment by adelarsq** [comment]
It's a missing feature. I will keep this issue open for now.

**Comment by chetra-seng** [comment]
@adelarsq Just a small update on my case. By enabling kitty image protocol on Wezterm, I was able to render images with your plugin inside Tmux :) Might be great if you could update the doc a bit to make sure newcomers don't have the same problem with Tmux and Wezterm

**Comment by adelarsq** [comment]
@chetra-seng Cool! Thanks for the confirmation. I will add this information on the docs.
