### ISSUE TITLE
Image Preview does not work

### ISSUE THREAD

**Issue by Pix3lexe** [adelarsq/image_preview.nvim#18]
When I press `<leader>p` on an image in NvimTree nothing happens. However when I press `<leader>p` on a non-image I get the correct message "No preview for file ..." so the keybind is working.

**Machine:**
Arch Linux

**Terminal:**
Kitty

**Nvim Version:**
v0.10.2

**Comment by mejistus** [comment]
![image](https://github.com/user-attachments/assets/7f947525-a6a0-44ec-a6fc-a947020f2c8f)
In file `~/.local/share/nvim/lazy/image_preview.nvim/lua/image_preview/init.lua`, you will find this line as the exact commands.So if you're not sure what's the problems is, you can delete the word `silent`, and press keybinds to see what error it will output.
You may install `icat` first because the default command used it.

**Comment by Pix3lexe** [comment]
After installing icat and adding it to my PATH (and after deleting the `silent`) I get this error while trying to preview a picture

![image](https://github.com/user-attachments/assets/32f7aa91-1289-4897-b4e3-22b2a3de5225)

**Comment by mejistus** [comment]
> After installing icat and adding it to my PATH (and after deleting the `silent`) I get this error while trying to preview a picture
> 
> ![image](https://private-user-images.githubusercontent.com/123319063/376027392-32f7aa91-1289-4897-b4e3-22b2a3de5225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTYyNzQsIm5iZiI6MTcyODgxNTk3NCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI3MzkyLTMyZjdhYTkxLTEyODktNDg5Ny1iNGUzLTIyYjJhM2RlNTIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMDM5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTk5ZTc5M2U4MzMzZjk0YjE0MTI1MTk0NDE1ZTI5ZTA2YzY1NGJjZTEwYWZjMWJmMWM5NTJiODg3ZmEwMGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X5xrYE8w8qU3FVxLACm8CFk3WQnElxYqqIzIYek5jYA)

You need to enable Kitty's remote control feature. You can do this by adding the prefix kitty -o enable_remote_control=true to the command, as shown in my screenshot above.

**Comment by Pix3lexe** [comment]
Thank you it works now. Is it normal that it opens a whole new window? (See the comparison between the screenshot from the README and mine)
I don't know if its just a difference between neo-tree and NvimTree

![image](https://github.com/user-attachments/assets/49221960-4db4-49a1-9f23-274a750888be)
![image](https://github.com/user-attachments/assets/5d1517bb-56c6-422e-82a6-6c886525e3fb)

**Comment by mejistus** [comment]
> Thank you it works now. Is it normal that it opens a whole new window? (See the comparison between the screenshot from the README and mine) I don't know if its just a difference between neo-tree and NvimTree
> 
> ![image](https://private-user-images.githubusercontent.com/123319063/376029078-49221960-4db4-49a1-9f23-274a750888be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTgzOTgsIm5iZiI6MTcyODgxODA5OCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MDc4LTQ5MjIxOTYwLTRkYjQtNDlhMS05ZjIzLTI3NGE3NTA4ODhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTE0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWQ4MDQ1YmZmYjUzODFkYTUwNTRhODRiZWRjZWIxNTFkMzg4NGUyNGRlMTVhOTUyZTRmYzIyY2Q1MzI4NjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DO3awgk2cXLPoESjkqjDhVM1HmtKPLxn6IRn-lj7Tsw) ![image](https://private-user-images.githubusercontent.com/123319063/376029135-5d1517bb-56c6-422e-82a6-6c886525e3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTgzOTgsIm5iZiI6MTcyODgxODA5OCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MTM1LTVkMTUxN2JiLTU2YzYtNDIyZS04MmE2LTZjODg2NTI1ZTNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTE0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTBhMzQ4ZmQyNDMwODJiMzBkY2VlMTMyZTMyZDQ0MjgwMmI4OGQzMDFhYWYzY2JkN2QyMzk4YjdhMTAzYTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZQS9U0hxsiErO-T-mgOjd8OXViEsliQcvUaXCTQ0t1w)

Sorry, I might not be able to help you, as I’m facing the same issue. It opens a separate image window, and I’m using Neo-tree.

**Comment by mejistus** [comment]
> Thank you it works now. Is it normal that it opens a whole new window? (See the comparison between the screenshot from the README and mine) I don't know if its just a difference between neo-tree and NvimTree
> 
> ![image](https://private-user-images.githubusercontent.com/123319063/376029078-49221960-4db4-49a1-9f23-274a750888be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkzMTgsIm5iZiI6MTcyODgxOTAxOCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MDc4LTQ5MjIxOTYwLTRkYjQtNDlhMS05ZjIzLTI3NGE3NTA4ODhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2QxNjIwM2UxM2Q3ZDZjZWViMTg5NDliNGUwNTg2MzA5ODlmMWQ4NmQ3ODAzZGIyMzc0OWJlM2QyZTdhOWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e0BARF5eFHxmOs2pPk71a1KH3h7UuW3J2UdNilNMj_w) ![image](https://private-user-images.githubusercontent.com/123319063/376029135-5d1517bb-56c6-422e-82a6-6c886525e3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkzMTgsIm5iZiI6MTcyODgxOTAxOCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MTM1LTVkMTUxN2JiLTU2YzYtNDIyZS04MmE2LTZjODg2NTI1ZTNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTVkNDY1MDNhMDkzNGMxMDA2ZjBkYzBkYTIzNjUxYjJhOWNjYWRmMzVmYzhjY2I0NDI1ZjQwZWMyZDc1MDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-TmtkihOHFAkPNVVFvd5HFRrHmihYBn1TOlXftmNakM)

Bro, I think I found a solution:

The key issue is how to make Kitty allow allow_remote_control. In the previous method, using kitty -o resulted in a new window being opened. The current solution is to use kitten --to to connect to the UNIX socket, which avoids opening a new Kitty window.

Here’s what you need to do:

Add the following lines to your kitty.conf:

`
allow_remote_control socket
listen_on unix:/tmp/mykitty
`
This will create a socket in /tmp when you open Kitty. The socket will be named something like /tmp/mykitty-xyz, where xyz is a random string.

Since the random string is unknown, you’ll need to use a bash command to get its value. It’s recommended to set an environment variable like this:

`
export KITTY_LISTEN_ON=$(ls /tmp | grep mykitty)
`
After that, modify your command to something like this:

`
command = 'silent !kitten @ launch --type=window --to unix:/tmp/$KITTY_LISTEN_ON kitten icat --hold '
silent prevents the text from rearranging and causing confusion.
`

**Comment by Mejistus** [comment]
> Thank you it works now. Is it normal that it opens a whole new window? (See the comparison between the screenshot from the README and mine) I don't know if its just a difference between neo-tree and NvimTree
> 
> ![image](https://private-user-images.githubusercontent.com/123319063/376029078-49221960-4db4-49a1-9f23-274a750888be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkzMTgsIm5iZiI6MTcyODgxOTAxOCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MDc4LTQ5MjIxOTYwLTRkYjQtNDlhMS05ZjIzLTI3NGE3NTA4ODhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2QxNjIwM2UxM2Q3ZDZjZWViMTg5NDliNGUwNTg2MzA5ODlmMWQ4NmQ3ODAzZGIyMzc0OWJlM2QyZTdhOWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e0BARF5eFHxmOs2pPk71a1KH3h7UuW3J2UdNilNMj_w) ![image](https://private-user-images.githubusercontent.com/123319063/376029135-5d1517bb-56c6-422e-82a6-6c886525e3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkzMTgsIm5iZiI6MTcyODgxOTAxOCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MTM1LTVkMTUxN2JiLTU2YzYtNDIyZS04MmE2LTZjODg2NTI1ZTNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTVkNDY1MDNhMDkzNGMxMDA2ZjBkYzBkYTIzNjUxYjJhOWNjYWRmMzVmYzhjY2I0NDI1ZjQwZWMyZDc1MDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-TmtkihOHFAkPNVVFvd5HFRrHmihYBn1TOlXftmNakM)

It works.

**Comment by mejistus** [comment]
> allow_remote_control socket listen_on unix:/tmp/mykitty
This line is
`
allow_remote_control socket 
`
`
listen_on unix:/tmp/mykitty
`
It works on my PC.

**Comment by Pix3lexe** [comment]
Thanks bro it finally works :)
I don't know if the developer should maybe include this in the README or update the code.

**Comment by mejistus** [comment]
> > Thank you it works now. Is it normal that it opens a whole new window? (See the comparison between the screenshot from the README and mine) I don't know if its just a difference between neo-tree and NvimTree
> > ![image](https://private-user-images.githubusercontent.com/123319063/376029078-49221960-4db4-49a1-9f23-274a750888be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkzMTgsIm5iZiI6MTcyODgxOTAxOCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MDc4LTQ5MjIxOTYwLTRkYjQtNDlhMS05ZjIzLTI3NGE3NTA4ODhiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2QxNjIwM2UxM2Q3ZDZjZWViMTg5NDliNGUwNTg2MzA5ODlmMWQ4NmQ3ODAzZGIyMzc0OWJlM2QyZTdhOWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e0BARF5eFHxmOs2pPk71a1KH3h7UuW3J2UdNilNMj_w) ![image](https://private-user-images.githubusercontent.com/123319063/376029135-5d1517bb-56c6-422e-82a6-6c886525e3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTkzMTgsIm5iZiI6MTcyODgxOTAxOCwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDI5MTM1LTVkMTUxN2JiLTU2YzYtNDIyZS04MmE2LTZjODg2NTI1ZTNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTVkNDY1MDNhMDkzNGMxMDA2ZjBkYzBkYTIzNjUxYjJhOWNjYWRmMzVmYzhjY2I0NDI1ZjQwZWMyZDc1MDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-TmtkihOHFAkPNVVFvd5HFRrHmihYBn1TOlXftmNakM)
> 
> Bro, I think I found a solution:
> 
> The key issue is how to make Kitty allow allow_remote_control. In the previous method, using kitty -o resulted in a new window being opened. The current solution is to use kitten --to to connect to the UNIX socket, which avoids opening a new Kitty window.
> 
> Here’s what you need to do:
> 
> Add the following lines to your kitty.conf:
> 
> `allow_remote_control socket listen_on unix:/tmp/mykitty` This will create a socket in /tmp when you open Kitty. The socket will be named something like /tmp/mykitty-xyz, where xyz is a random string.
> 
> Since the random string is unknown, you’ll need to use a bash command to get its value. It’s recommended to set an environment variable like this:
> 
> `export KITTY_LISTEN_ON=$(ls /tmp | grep mykitty)` After that, modify your command to something like this:
> 
> `command = 'silent !kitten @ launch --type=window --to unix:/tmp/$KITTY_LISTEN_ON kitten icat --hold ' silent prevents the text from rearranging and causing confusion.`

Correct:
`export KITTY_LISTEN_ON=$(ls /tmp | grep mykitty)` This line is not needed, because this env variable is created by kitty itself.
It runs wrongly if there are 2 kitty instances or more.
Just delete this line.

**Comment by Pix3lexe** [comment]
If I delete this variable I get this error
![image](https://github.com/user-attachments/assets/fbf60d86-304e-4fee-b594-5b0520402ea9)
Something broke, now it doesn't even work if I add the env variable again

**Comment by mejistus** [comment]
> If I delete this variable I get this error ![image](https://private-user-images.githubusercontent.com/123319063/376034179-fbf60d86-304e-4fee-b594-5b0520402ea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjMzMTIsIm5iZiI6MTcyODgyMzAxMiwicGF0aCI6Ii8xMjMzMTkwNjMvMzc2MDM0MTc5LWZiZjYwZDg2LTMwNGUtNGZlZS1iNTk0LTViMDUyMDQwMmVhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMjM2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjYyNGU2OGU2MjZkM2EyYmNjNzFlMTg3OWVjODI5ODEyOGE1NmZmZTc0ZmM4YzRhYmYzNzg0NDMyMmJmM2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FpryW-CUbRkTH1UJYanlNIzOj1keg-Nx7o4JNIANT_M) Something broke, now it doesn't even work if I add the env variable again

Because the env variable $KITTY_LISTEN_ON is a full type.You should use `--to $KITTY_LISTEN_ON` rather than `--to unix:/tmp/$KITTY_LISTEN_ON`.
You can run `echo $KITTY_LISTEN_ON` in kitty to check it.

**Comment by Pix3lexe** [comment]
Ahh okay, thank you again bro :)

**Comment by mejistus** [comment]
> Ahh okay, thank you again bro :)

You're welcome :)
