### ISSUE TITLE
feature: neo-tree support

### ISSUE THREAD

**Issue by luxus** [adelarsq/image_preview.nvim#3]
hello,
your plugin looks good, i use wezterm, linux and macOS
but as a filemanager i do use neo-tree. are you planing to support it?

**Comment by adelarsq** [comment]
Yes. I pretend to support all major file tree plugins, even NerdTree.
But I can't say when since on this month I am pretty busy with work.
I will keep this open as a feature request.

**Comment by pysan3** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/831#discussioncomment-5987459

This should work @luxus ;)

**Comment by adelarsq** [comment]
@pysan3 Thanks for the hint!

I added the config on the docs, since for this plugin I think that is the best way.

**Comment by pysan3** [comment]
Thanks! I think you forgot the backtick lua tho @adelarsq 

The codeblock is not syntax highlighted.

**Comment by adelarsq** [comment]
@pysan3 Thanks again :)
