### ISSUE TITLE
Directory name change

### ISSUE THREAD

**Issue by homaji** [adelarsq/image_preview.nvim#5]
Hi.

I use Windows 10 and Neovim 0.8.2 with wezterm.

I use Packer for plugin manager.
And Directory name "lua" can't load image_preview script.
(:scriptnames don't show the file name.)

Can you change Directory name to "plugin" ?

**Comment by adelarsq** [comment]
@homaji Thanks for the report! I did some changes on the directories. Can you confirm that is ok?

Edit: Closing issue for now.
