### ISSUE TITLE
picture doesn't appear on screen and closed.

### ISSUE THREAD

**Issue by soulinland82** [adelarsq/image_preview.nvim#6]
When I click <leader>p then wezterm split horizenly and picture doesn't appear 
and immediately close and ask me like 'would you like to continue?'
and <leader>p, this key doesn't work well.
So now I close it and I type wezterm imgcat command and open file manually.

**Comment by adelarsq** [comment]
@soulinland82 This is a bug with Wezterm.

For now you can use the nightly version that has a fix for it. Just for PowerShell through.

I will close this issue since I can't make a fix here. Thanks for the report :)
