### ISSUE TITLE
kitty support

### ISSUE THREAD

**Issue by raffaelemancuso** [adelarsq/image_preview.nvim#8]
Does this support kitty? Or is kitty support planned?

**Comment by adelarsq** [comment]
@raffaem Yes. I plan to add support for every terminal emulator that has support for images. But I don't know when I will be able to do that.

I will add Kitty as the next terminal to support. I am keeping this issue open.

**Comment by SichangHe** [comment]
Might be useful reference: https://github.com/edluffy/hologram.nvim

**Comment by ejconlon** [comment]
Hello all, I forked and added kitty support: https://github.com/ejconlon/image_preview.nvim/blob/main/lua/image_preview/init.lua . I did some auto-formatting with stylua and such, so it may not be to your liking.

**Comment by adelarsq** [comment]
@ejconlon Cool! I will do an update. Thanks for share.

**Comment by adelarsq** [comment]
@ejconlon Based on the code provided I did some changes on this plugin (https://github.com/adelarsq/image_preview.nvim/commit/21910cf664f784913036bb924ebb5eb23c9f03f0). Please test if you can. I don't have any Linux machine right now.

I am closing the issue. Feel free to reach me. Thanks again @ejconlon !

**Comment by SichangHe** [comment]
Suggestion: would be better if the README indicates dependencies on either Wezterm or Kitty, not just Wezterm!

**Comment by adelarsq** [comment]
@SichangHe Yes. I already added on the features list. Can you provide one screenshot using it?

**Comment by SichangHe** [comment]
Well, I was trying to make SSH work as well but couldn't: https://github.com/SichangHe/adelarsq--image_preview.nvim/tree/kitty-over-ssh, https://github.com/kovidgoyal/kitty/discussions/6017.

**Comment by SichangHe** [comment]
![image](https://github.com/adelarsq/image_preview.nvim/assets/84777573/88c2dcac-1332-4c64-91af-a009e73e7399)

Screenshot. That was difficult.

**Comment by adelarsq** [comment]
@SichangHe Thanks for the help on this. For ssh I am also interested, but will take some time to dig over.

**Comment by ovidius72** [comment]
It looks like it doesn't work from inside TMUX.
Maybe this is the relevant issue? https://github.com/kovidgoyal/kitty/discussions/6017

**Comment by ejconlon** [comment]
@ovidius72 You might need socket control, see the readme on my fork.

**Comment by ovidius72** [comment]
@ejconlon  Used you fork with the suggested kitty configuration and it just work. 
Thank you very much :-)
